import { cspellConfig } from '@kitschpatrol/cspell-config'

export default cspellConfig({
	ignorePaths: ['test/fixtures/**/*', 'test/**/*'],
	words: [
		'addopts',
		'archs',
		'asyncio',
		'autopep',
		'bdist',
		'bumpversion',
		'cibuildwheel',
		'dagster',
		'docformatter',
		'doctest',
		'doctests',
		'dunder',
		'envfile',
		'filterwarnings',
		'isort',
		'mccabe',
		'noqa',
		'norecursedirs',
		'optionflags',
		'parentdir',
		'pydocstyle',
		'pythonpath',
		'pyupgrade',
		'sdist',
		'showcontent',
		'smol',
		'tbump',
		'testpaths',
		'towncrier',
		'typeshed',
		'yapf',
	],
})
