import { cspellConfig } from '@kitschpatrol/cspell-config'

export default cspellConfig({
	ignorePaths: ['test/fixtures/**/*'],
	words: [
		'addopts',
		'archs',
		'asyncio',
		'autopep',
		'bdist',
		'bumpversion',
		'cibuildwheel',
		'distutils',
		'docformatter',
		'doctest',
		'doctests',
		'dunder',
		'envfile',
		'filterwarnings',
		'htmlcov',
		'isort',
		'jlpm',
		'mccabe',
		'metascope',
		'musllinux',
		'mypackage',
		'mypy',
		'noqa',
		'norecursedirs',
		'optionflags',
		'parentdir',
		'pycache',
		'pylib',
		'pylint',
		'pythonpath',
		'sdist',
		'setuptools',
		'showcontent',
		'smol',
		'tbump',
		'testpaths',
		'towncrier',
		'typeshed',
		'yapf',
	],
})
